#!/usr/bin/with-contenv sh

exec /usr/sbin/varnishd \
  -F \
  -f /etc/varnish/default.vcl \
  -a ${VARNISH_LISTEN_ADDRESS}:${VARNISH_LISTEN_PORT} \
  -T ${VARNISH_ADMIN_LISTEN_ADDRESS}:${VARNISH_ADMIN_LISTEN_PORT} \
  -s $VARNISH_STORAGE \
  $VARNISH_EXTRA_OPTS
